stages:
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-frontend:
  stage: build
  image: node:18
  script:
    - corepack enable
    - pnpm install --prod=false
    - pnpm run build
